shader.primitive.fragment=resource:///shaders/PrimitiveFragmentShader.glsl
shader.primitive.vertex=resource:///shaders/PrimitiveVertexShader.glsl
texture.example.smile=resource:///textures/example/smile.png
texture.gui.mainmenu.background=resource:///textures/gui/mainmenu/background.jpg
texture.gui.mainmenu.column=resource:///textures/gui/mainmenu/column.png
