shader.primitive.textured.fragment=resource:///shaders/default/PrimitiveTexturedFragmentShader.glsl
shader.primitive.textured.vertex=resource:///shaders/default/PrimitiveTexturedVertexShader.glsl
shader.primitive.colored.fragment=resource:///shaders/default/PrimitiveColoredFragmentShader.glsl
shader.primitive.colored.vertex=resource:///shaders/default/PrimitiveColoredVertexShader.glsl
texture.example.smile=resource:///textures/example/smile.png
texture.gui.mainmenu.background=resource:///textures/gui/mainmenu/background.jpg
texture.gui.mainmenu.column=resource:///textures/gui/mainmenu/column.png
model.gui.default.element=resource:///models/gui/default/element.obj
