font.gui.mainmenu.notoemoji.regular=resource:///fonts/Roboto-Bold.ttf
font.gui.mainmenu.roboto.bold=resource:///fonts/Roboto-Bold.ttf
font.gui.mainmenu.roboto.light=resource:///fonts/Roboto-Bold.ttf
font.gui.mainmenu.roboto.regular=resource:///fonts/Roboto-Bold.ttf
shader.primitive.textured.fragment=resource:///shaders/default/PrimitiveTexturedFragmentShader.glsl
shader.primitive.textured.vertex=resource:///shaders/default/PrimitiveTexturedVertexShader.glsl
shader.primitive.colored.fragment=resource:///shaders/default/PrimitiveColoredFragmentShader.glsl
shader.primitive.colored.vertex=resource:///shaders/default/PrimitiveColoredVertexShader.glsl
shader.default.gui.textured.fragment=resource:///shaders/default/gui/DefaultTexturedElementFragmentShader.glsl
shader.default.gui.textured.vertex=resource:///shaders/default/gui/DefaultTexturedElementVertexShader.glsl
shader.default.gui.colored.fragment=resource:///shaders/default/gui/DefaultColoredElementFragmentShader.glsl
shader.default.gui.colored.vertex=resource:///shaders/default/gui/DefaultColoredElementVertexShader.glsl
texture.example.smile=resource:///textures/example/smile.png
texture.gui.mainmenu.background=resource:///textures/gui/mainmenu/background.jpg
texture.gui.mainmenu.column=resource:///textures/gui/mainmenu/column.png
texture.gui.mainmenu.column=resource:///textures/gui/mainmenu/column.png
model.gui.default.element=resource:///models/gui/default/element.obj
model.example.cube=resource:///models/example/cube.obj
